### ISSUE TITLE
question about reproducibility

### ISSUE THREAD

**Issue by nandobonf** [const-ae/mixdir#2]
Dear authors, 
thanks for the implementation of the algorithm, it is very useful.
How can I check for example for cluster reproducibility?
I noticed that without setting a seed, the clustering can change significantly.
Do I need to increase the number of repetitions?

**Comment by const-ae** [comment]
Hi Ferdinando,
thank you for the interest in the package and reaching out.
Yes, it is possible that you get different clusters in repeated runs on the same data because the method is randomly initialized. 

As you mention, the package provides the `repetitions` parameter to run the model multiple times and automatically select the solution with the largest ELBO (ie. smallest KL divergence). It is a simple loop around the model, implemented [here](https://github.com/const-ae/mixdir/blob/master/R/mixdir.R#L131). 
To monitor the reliability of the clustering, you can also just call the `mixdir()` multiple time yourself and manually inspect the distribution of ELBOs.

If you find that some results have a good ELBO but the clusterings differ considerably, this could be because the information in the data is not strong enough to identify the result reliably. In that case, could you maybe share the data so I can take a look myself?

Best Regards,
Constantin

**Comment by nandobonf** [comment]
Thanks for the swift reply.
Indeed, my problem was running the algorithm with 1 repetition only. Increasing reps to 10 or more gives me more stable results.
I attach here my dataset, it seems however that is not clusterable (ie, I can found 1 big cluster and some "outliers"). 
Can you confirm this? 
Thanks again for your time.

[dat.txt](https://github.com/const-ae/mixdir/files/4311689/dat.txt)

**Comment by const-ae** [comment]
Thanks for the data.

> I attach here my dataset, it seems however that is not clusterable (ie, I can found 1 big cluster and some "outliers").


Yes, I get the same results. This alluvial plot shows you the assigned class membership after each clustering:

``` r
library(tidyverse)
library(mixdir)


df <- read_csv("~/Downloads/dat.txt")
#> Parsed with column specification:
#> cols(
#>   .default = col_character()
#> )
#> See spec(...) for full column specifications.


# Make 5 different clusterings and look at consitency.
res <- map_df(1:5, function(idx){
  res <- mixdir(df, repetitions = 25)
  data.frame(class=res$pred_class, ind=seq_len(length(res$pred_class)), run = idx)
})

# Make alluvial plot to show result
res %>%
  as_tibble() %>%
  mutate(class=as.character(class),
         run=as.factor(paste0("run", run))) %>%
  spread(run, class) %>%
  group_by_at(vars(starts_with("run")))  %>%
  summarize(freq=n()) %>%
  {alluvial::alluvial(.[,1:5], freq = .$freq)}
```

![](https://i.imgur.com/1ukMtce.png)

<sup>Created on 2020-03-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

You could also play around with `alpha` and `beta` parameter and see how they affect the clustering. This is for example the result if I set `alpha = 10`.

![](https://i.imgur.com/GyqypMZ.png)

**Comment by nandobonf** [comment]
Fantastic! Many Thanks
